version: '3'
services:
  apache2:
    build: .
    hostname: api.carteirarica.com.br
    restart: always
    volumes:
      - etcletsencrypt:/etc/letsencrypt
      - varletsencrypt:/var/lib/letsencrypt
    ports:
      - "8070:80"
      - "443:443"
    environment:
      LETS_ENCRYPT_EMAIL: "contato@carteirarica.com.br"
      LETS_ENCRYPT_DOMAINS: "api.carteirarica.com.br"

volumes:
  varletsencrypt:
  etcletsencrypt:
